# Generated by Django 3.0 on 2020-12-05 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_picture',
        ),
    ]
