# Generated by Django 3.0 on 2020-12-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0003_user_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_picture',
        ),
    ]
