# Generated by Django 3.0 on 2020-12-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donuts', '0004_delete_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_image', models.ImageField(upload_to='image/')),
                ('user_image_after', models.CharField(max_length=100)),
            ],
        ),
    ]
