# Generated by Django 3.0 on 2020-12-06 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donuts', '0005_user_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_picture',
        ),
    ]
